name: Test CI

on:
  push:
    
jobs:
  triage:
    #  check and make sure action wasnt made by github while committing changes
    # ! uncomment
    # if: >-
    #   github.event.push.pusher.name != 'github' 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: "get version"
      env:
        VERSION: | grep "version:" pubspec.yaml
      run: | echo ${{env.VERSION}}
    
    # read pubspec file for version
    # update version
    # write pubspec file with version
    # commit changes
    # create tag with version name