name: Test CI

on:
  push:
    
jobs:
  triage:
    #  check and make sure action wasnt made by github while committing changes
    # ! uncomment
    # if: >-
    #   github.event.push.pusher.name != 'github' 
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2

    - name: "get and update version"
      # env:
      #   VERSION: | grep "version:" pubspec.yaml
      run: ./.github/scripts/setup_version.sh
    
    #  add conditions to choosing version

    - name: "write pubspec file with version"
      env: 
        VERSION_NEW: ${{env.VERSION_MINOR}}
      run: ./.github/scripts/effect_version.sh
      
    # commit changes

    - name: Add changes to Git tracking
      run: git add -A .

    - name: Commit changes
      uses: gha-utilities/workspace-commit@v0.0.4
      with:
        author: "koa_runner"
        email: "runner@withkoa.com"
        message: "Bump version ${{env.VERSION_MINOR}}"
        all: true

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    - name: Tests
      run: echo ${{ github.ref }}

    - name: Initialize Pull Request
      env: 
        VERSION_NEW: ${{env.VERSION_MINOR}}
      uses: gha-utilities/init-pull-request@v0.0.9
      with:
        pull_request_token: ${{ secrets.GITHUB_TOKEN }}
        head: ${{ github.ref }}
        base: staging
        title: 'Updates for Production'
        body: 'Approve and merge to push a release build for ${{env.VERSION_NEW}}'

    # create tag with version name