name: Test CI

on:
  push:
    
jobs:
  triage:
    #  check and make sure action wasnt made by github while committing changes
    # ! uncomment
    # if: >-
    #   github.event.push.pusher.name != 'github' 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: "get and update version"
      # env:
      #   VERSION: | grep "version:" pubspec.yaml
      run: ./.github/scripts/setup_version.sh
    
    - name: "update version"
      env: 
        VERSION_NEW: VERSION_MINOR
      run: sed -i '' "s/version: ${{VERSION}}/version: ${{VERSION_NEW}}/g" pubspec.yaml


    #  add conditions to choosing version

    - name: "write pubspec file with version"
      run: 

    # commit changes
    # create tag with version name