name: Test CI

on:
  push:
    
jobs:
  triage:
    #  check and make sure action wasnt made by github while committing changes
    # ! uncomment
    # if: >-
    #   github.event.push.pusher.name != 'github' 
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v1

    - name: "get and update version"
      # env:
      #   VERSION: | grep "version:" pubspec.yaml
      run: ./.github/scripts/setup_version.sh
    
    #  add conditions to choosing version

    - name: "write pubspec file with version"
      env: 
        VERSION_NEW: ${{env.VERSION_MINOR}}
      run: ./.github/scripts/effect_version.sh

    - name: action-push
      uses: ludeeus/action-push@0.0.1
      env:
        ACTION_MAIL: "runner@withkoa.com"
        ACTION_NAME: "koa_runner"
        ACTION_BRANCH: ${{ github.ref }}
        ACTION_MESSAGE: "Bump version ${{env.VERSION_MINOR}}"
      secrets: ${{secrets.GITHUB_TOKEN}}
      

    # commit changes
    # create tag with version name