name: Test CI

on:
  push:
    
jobs:
  triage:
    #  check and make sure action wasnt made by github while committing changes
    # ! uncomment
    # if: >-
    #   github.event.push.pusher.name != 'github' 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    # read pubspec file for version
    - name: "get and update version"
      # env:
      #   VERSION: | grep "version:" pubspec.yaml
      run: ./.github/scripts/setup_version.sh
    
    # update version
    - name: "update version"
      run: echo ${{VERSION}}
    # - run: echo version1 ${{VERSION_1}}
    # - run: echo version2 ${{VERSION_2}}
    # - run: echo version3 ${{VERSION_3}}

    # write pubspec file with version
    # commit changes
    # create tag with version name