name: Test CI

on:
  push:
    # branches:
    # - staging
    
jobs:
  build:
    runs-on: macOS-latest
    steps:
    
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.6'
    
    - name: Flutter clean-up
      run: cd ios && pod deintegrate && cd ..
    - run: flutter clean
    
    # Get flutter dependencies.
    - name: Flutter setup
      run: flutter pub get
    
    # Check for any formatting issues in the code.
    # - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    # - run: flutter analyze .

    # - run: flutter pub run build_runner build --delete-conflicting-outputs
    
    # Run tests
    - run: flutter test
    
    # Build apk
    # - name: Build process for Android
    #   run: flutter build apk --release

    # # Firebase disctribution
    # - name: Upload to firebase app distribution
    #   uses: wzieba/Firebase-Distribution-Github-Action@v1
    #   with:
    #     appId: ${{secrets.FIREBASE_APP_ID}}
    #     serviceCredentialsFile: .github/secrets/oka-cash-e78b8f02be55.json
    #     # groups: team,private testers,Interns
    #     groups: test1
    #     file: build/app/outputs/apk/release/app-release.apk

      # FLOW FOR IOS deployment
    
    # - name: Build process For iOS
    #   run: brew install gnupg
    # - name: Setup provisioning profile
    #   env:
    #     IOS_KEYS: ${{secrets.IOS_KEYS}}
    #   run: ./.github/secrets/decrypt_secrets.sh

    - name: Pod install
      run: flutter build ios --release --no-codesign

    - name: iOS Magic
      uses: yukiarrr/ios-build-action@v1.3.3
      with:
        project-path: ios/Runner.xcodeproj
        workspace-path: ios/Runner.xcworkspace
        p12-base64: ${{ secrets.P12_BASE64 }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
        certificate-password: ${{ secrets.IOS_KEYS }}

    # - name: Upload to firebase app distribution
    #   uses: wzieba/Firebase-Distribution-Github-Action@v1
    #   with:
    #     appId: ${{secrets.FIREBASE_APP_ID}}
    #     serviceCredentialsFile: .github/secrets/oka-cash-e78b8f02be55.json
    #     # groups: team,private testers,Interns
    #     groups: test1
    #     file: build/Koa.ipa